### ISSUE TITLE
I got an error when using the oneclient_install.yml 

### ISSUE THREAD

**Issue by iblanque** [indigo-dc/tosca-types#104]
Hi,

I am deploying an infrastructure (using ORCHENT) described in https://raw.githubusercontent.com/indigo-dc/tosca-types/master/examples/eubiosteo_client.yml. It uses oneclient_install.yml, and I got an error on the operations done in this module:

...
TASK [Install Ubuntu oneclient package] ****************************************
ok: [158.42.105.6_22]

TASK [Add root user to fuse group] *********************************************
fatal: [158.42.105.6_22]: FAILED! => {"changed": false, "failed": true, "msg": "Group fuse does not exist"}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
158.42.105.6_22            : ok=13   changed=0    unreachable=0    failed=1   
158.42.105.6_22            : ok=13   changed=0    unreachable=0    failed=1   

ERROR executing playbook (1/1)
ERROR executing task onedata_client_node_conf_onedata_client_node: (3/3)

***************************************************************************
...

It seems that the task:

  - name: Add {{ansible_user}} user to fuse group
    user: name={{ansible_user}} append=yes groups=fuse
    when: ansible_distribution == "Ubuntu"

is not working as the fuse group is not created. It was created before when installing onedataclient.

Can you check?

Many thanks

**Comment by micafer** [comment]
A fix proposed in commit 41041c3fd2ea0683f5861e84a1c352c8977f69b6.

**Comment by micafer** [comment]
Merged to master.
