### ISSUE TITLE
Use policy property instead of metadata to select SLA

### ISSUE THREAD

**Issue by alberto-brigandi** [indigo-dc/tosca-types#107]
It seems that the `metadata` field has been added in the v1.1 of the TOSCA YAML standard. As the `properties` field is already available in v1.0, couldn't we use that instead?

[TOSCA YAML v1.0 policy definition](http://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.0/TOSCA-Simple-Profile-YAML-v1.0.html#DEFN_ELEMENT_POLICY_DEF)
[TOSCA YAML v1.1 policy definition](http://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.1/TOSCA-Simple-Profile-YAML-v1.1.html#DEFN_ELEMENT_POLICY_DEF)

**Comment by alberto-brigandi** [comment]
Here is a commit with the proposed change: 7b11456fffcf75438bded0f6229c0f1d1f86d988

**Comment by micafer** [comment]
Yes is better to maintain the compatibility with TOSCA v1.0.
